//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Content.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forum.Content.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywny.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracja.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Również niezalogowani użytkownicy mogą pisać w tym forum.
        /// </summary>
        public static string AllowAnonymous {
            get {
                return ResourceManager.GetString("AllowAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie razem.
        /// </summary>
        public static string AllTogether {
            get {
                return ResourceManager.GetString("AllTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj wszystkich słów razem.
        /// </summary>
        public static string AllWordsTogether {
            get {
                return ResourceManager.GetString("AllWordsTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogłoszenie.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogłoszenia.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce na ogłoszenia.
        /// </summary>
        public static string AnnouncementsPlaceholder {
            get {
                return ResourceManager.GetString("AnnouncementsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonim.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załączniki.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć do listy.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do tematu.
        /// </summary>
        public static string BackToTopic {
            get {
                return ResourceManager.GetString("BackToTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przez.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odróżniaj wielkość liter.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień swoje hasło.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string ConfirmPw {
            get {
                return ResourceManager.GetString("ConfirmPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło i potwierdzenie się nie zgadzają.
        /// </summary>
        public static string ConfirmPwError {
            get {
                return ResourceManager.GetString("ConfirmPwError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz nowy.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślny.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na pewno chcesz to usunąć?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj avatar.
        /// </summary>
        public static string EditAvatar {
            get {
                return ResourceManager.GetString("EditAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} jest wymagane..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazane.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fora.
        /// </summary>
        public static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyklejony.
        /// </summary>
        public static string Glued {
            get {
                return ResourceManager.GetString("Glued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupy.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaczniki HTML.
        /// </summary>
        public static string HTMLMarkers {
            get {
                return ResourceManager.GetString("HTMLMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odwróć wynik wyszukiwania.
        /// </summary>
        public static string InverseSearchResults {
            get {
                return ResourceManager.GetString("InverseSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowa kluczowe.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatni post.
        /// </summary>
        public static string LastPost {
            get {
                return ResourceManager.GetString("LastPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia odpowiedź.
        /// </summary>
        public static string LastReply {
            get {
                return ResourceManager.GetString("LastReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} musi mieć przynajmniej {2} znaków..
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LoginNow {
            get {
                return ResourceManager.GetString("LoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj profil.
        /// </summary>
        public static string ManageYourProfile {
            get {
                return ResourceManager.GetString("ManageYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znacznik.
        /// </summary>
        public static string Marker {
            get {
                return ResourceManager.GetString("Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomości.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten użytkownik jest już moderatorem w tym forum..
        /// </summary>
        public static string ModeratorExists {
            get {
                return ResourceManager.GetString("ModeratorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderatorzy w.
        /// </summary>
        public static string ModeratorsIn {
            get {
                return ResourceManager.GetString("ModeratorsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista moderatorów.
        /// </summary>
        public static string ModeratorsList {
            get {
                return ResourceManager.GetString("ModeratorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negacja.
        /// </summary>
        public static string Negation {
            get {
                return ResourceManager.GetString("Negation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOWY.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załóż konto..
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wiadomość.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy temat.
        /// </summary>
        public static string NewTopic {
            get {
                return ResourceManager.GetString("NewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy temat w.
        /// </summary>
        public static string NewTopicIn {
            get {
                return ResourceManager.GetString("NewTopicIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak forum.
        /// </summary>
        public static string NoForum {
            get {
                return ResourceManager.GetString("NoForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak moderatorów.
        /// </summary>
        public static string NoModerators {
            get {
                return ResourceManager.GetString("NoModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak wątków.
        /// </summary>
        public static string NoThreads {
            get {
                return ResourceManager.GetString("NoThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak tematów.
        /// </summary>
        public static string NoTopics {
            get {
                return ResourceManager.GetString("NoTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój profil.
        /// </summary>
        public static string OwnProfile {
            get {
                return ResourceManager.GetString("OwnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post którego szukasz nie istnieje..
        /// </summary>
        public static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post został pomyślnie zgłoszony do moderacji..
        /// </summary>
        public static string PostReported {
            get {
                return ResourceManager.GetString("PostReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posty.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postów na stronę.
        /// </summary>
        public static string PostsPerPage {
            get {
                return ResourceManager.GetString("PostsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prywatne wątki.
        /// </summary>
        public static string PrivateThreads {
            get {
                return ResourceManager.GetString("PrivateThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiczne.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresat.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętać mnie?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedzi.
        /// </summary>
        public static string Replies {
            get {
                return ResourceManager.GetString("Replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź do tematu.
        /// </summary>
        public static string ReplyToTopic {
            get {
                return ResourceManager.GetString("ReplyToTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłoś.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgłaszanie posta.
        /// </summary>
        public static string ReportAPost {
            get {
                return ResourceManager.GetString("ReportAPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij wiadomość.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas sesji.
        /// </summary>
        public static string SessionTime {
            get {
                return ResourceManager.GetString("SessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temat.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tematy.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wgraj nowy.
        /// </summary>
        public static string UploadNew {
            get {
                return ResourceManager.GetString("UploadNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użyj swojego konta aby się zalogować..
        /// </summary>
        public static string UseLocalAccount {
            get {
                return ResourceManager.GetString("UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetleń.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowo.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
