// <auto-generated />
namespace Forum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class private_msgs2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(private_msgs2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701021726225_private_msgs2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
